travis:
  secure:
    BINSTAR_TOKEN: adf/o2wDb6onmPgbFnW9TZzzgsRL6Naw5ukVZy/3l2IHAya4AFs6h6MZL2RXbo74OUdhndRb8EGff3oh/trOVkPlC8EdCuI2J/yYOsjY1QbhtA9nCUg+GI8ze23VoabYpKNXzZE265YLXSlqGhFBW/T5mytoysLqOUJuOyvvGbrgThi+ok5xARyJ7BZrRCHC+J6UwJHsGjiYwQVLvrE7BlloDyEzsqSaQN2k676XPmiyRHtZnScJRxZ+75LYu/GcLcb4aP3tAq6JOgq5ux94dpX8hlqx4B2NAcs9zrvWE2kWzTVfISXadV4w3Hy3fecTYxDb9p5x9Xo7q0JneKpR0QR1/pEhH/zOmjMlWmPyraQg87jrnDLBSi4raJGMqEcWmO6efndrl5OZUPEoOoXLd3ZQDGEzJeWObPdYHlWmDCIAK2cZNKThX2dmLiEaG8Ra137A3gcfkSvA8XoeqJVkTCVrGLpMX+fmsLJN4jdYgNkAzKFdgJvFZ0tCmaCtNOPshwY9KmoB1oobx41kLwt5bmSIBvYiBzgnVmzVl9/UDeN8jDanEYaveNRb8Im/v+xZ7uMmeqZnrXRYiLqeewwR3v9G7QJa6/Qbzmzl7lT4+HbNtTglzyGrEe0yD8K1/WNzqVTAscRpcIG5rE5VqwjndlJo6pOUWRB4VEzB58yc5Vc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
